### PR TITLE
fix formatting, added libs via cdn and fixed mixed content

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@anniezhou301 any reason for closing this?

**Comment by anniezhou301** [comment]
I don't really know you, sorry.. This is more of a private project of mine

**Comment by OmgImAlexis** [comment]
Well I found this project via Github's search, you should really look at the changes as they fix a lot of issues with your HTML and change the js to use a CDN instead of local files.

If you're just starting on Github I'd suggest you get use to random people submitting PRs. If you don't want that you should really be using BitBucket or Github private repos.

**Comment by anniezhou301** [comment]
Thanks for helping out :) It was really appreciated. I guess I'm still not that used to people trying submit pull requests. I was definitely surprised.

**Comment by codethejason** [comment]
Thank you for your generous help, OmgImAlexis! This is mainly a private project and we are currently seeking to turn this into a private repository until the website goes live. We will surely implement some of your changes, but it might not be through accepting the PR.

**Comment by OmgImAlexis** [comment]
@codethejason all's good. I just saw your repo using http and not https for your Google fonts link and I figured while I was here I might as well clean up the formatting since it was all over the place. Really all I did was reorganise the file and updated the js to use the same MaxCDN that you were using for another library. :+1:

**Comment by codethejason** [comment]
@OmgImAlexis Again, thank you for your suggestions. We have incorporated your non-formatting optimizations.

**Comment by OmgImAlexis** [comment]
@codethejason was there a reason you didn't just accept the PR? That's how gitflow is meant to work.

Also some of the things I added weren't just optimisations but actually security issues which haven't been added at all, again this is why I submitted a PR and not just opened an issue with an example of the changes.

**Comment by hackuc** [comment]
@OmgImAlexis The majority of the code was formatting and it would take a lot longer for us to go through each merge conflict. We have added the https to the calls and I don't seem to see any security issues you have recommended. If you can bring them up, the changes can be recommitted. 

Also, our organization that this is for is not accepting outside commits/PRs. It is public for now to show other members who do not have github accounts. We can consider issues though.

**Comment by OmgImAlexis** [comment]
Oh I give up, honestly this is the way you keep people away from ever helping you on here. Github is about sharing and helping people. All you did was take part of my fix and attempt to add them yourself, that's not how Github it meant to be used at all.

Also there was only a handful of changes I made and you can easily see the formatting fixes. I really don't understand why this wasn't just merged.
I'd suggest you move to another platform if you don't want PRs.

**Comment by hackuc** [comment]
Thank you, we appreciate your help and will definitely consider moving to another platform.

**Pull request closed without merging**
